CREATE TABLE IF NOT EXISTS "cloudflare_security_settings" (
  "id" TEXT NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "mode" TEXT NOT NULL DEFAULT 'OFF',
  "turnstile_site_key" TEXT NOT NULL DEFAULT '',
  "turnstile_secret_key" TEXT NOT NULL DEFAULT '',
  "turnstile_mode" TEXT NOT NULL DEFAULT 'managed',
  "protect_login" BOOLEAN NOT NULL DEFAULT true,
  "protect_register" BOOLEAN NOT NULL DEFAULT true,
  "protect_forgot_password" BOOLEAN NOT NULL DEFAULT true,
  "protect_contact" BOOLEAN NOT NULL DEFAULT true,
  "protect_checkout" BOOLEAN NOT NULL DEFAULT true,
  "protect_support" BOOLEAN NOT NULL DEFAULT true,
  "protect_orders" BOOLEAN NOT NULL DEFAULT true,
  "protect_admin_login" BOOLEAN NOT NULL DEFAULT true,
  "whitelist_enabled" BOOLEAN NOT NULL DEFAULT false,
  "whitelist_ips" JSONB NOT NULL DEFAULT '[]',
  "whitelist_cidrs" JSONB NOT NULL DEFAULT '[]',
  "whitelist_emails" JSONB NOT NULL DEFAULT '[]',
  "whitelist_customer_ids" JSONB NOT NULL DEFAULT '[]',
  "last_verification_at" TIMESTAMP(3),
  "last_verification_status" TEXT,
  "rate_limit_enabled" BOOLEAN NOT NULL DEFAULT true,
  "risk_scoring_enabled" BOOLEAN NOT NULL DEFAULT true,
  "bot_detection_enabled" BOOLEAN NOT NULL DEFAULT true,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "cloudflare_security_settings_pkey" PRIMARY KEY ("id")
);

INSERT INTO "cloudflare_security_settings" (
  "id",
  "enabled",
  "mode",
  "turnstile_site_key",
  "turnstile_secret_key",
  "turnstile_mode",
  "protect_login",
  "protect_register",
  "protect_forgot_password",
  "protect_contact",
  "protect_checkout",
  "protect_support",
  "protect_orders",
  "protect_admin_login",
  "last_verification_at",
  "last_verification_status",
  "rate_limit_enabled",
  "created_at",
  "updated_at"
)
SELECT
  CONCAT('cfsec_', "id"),
  false,
  'OFF',
  "turnstile_site_key",
  "turnstile_secret_key",
  "turnstile_mode",
  "protect_login",
  "protect_signup",
  "protect_login",
  "protect_contact",
  "protect_checkout",
  "protect_tickets",
  "protect_checkout",
  "protect_login",
  "last_verification_at",
  "last_verification_status",
  "rate_limit_enabled",
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
FROM "system_security_settings"
WHERE NOT EXISTS (SELECT 1 FROM "cloudflare_security_settings")
ORDER BY "created_at" ASC
LIMIT 1;
