import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import test from "node:test"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..")
const read = (path: string) => readFileSync(`${root}/${path}`, "utf8")

test("IPAM canonical assignments are the write path and legacy tables are read-only fallback", () => {
  const ipam = read("lib/ipam-admin.ts")
  const migration = read("prisma/migrations/20260617_canonical_ip_pool_assignments/migration.sql")
  assert.match(ipam, /poolNodeAssignment\.upsert/)
  assert.match(ipam, /poolProductAssignment\.upsert/)
  assert.match(ipam, /db\.nodeIpPool\.findMany/)
  assert.match(ipam, /db\.productIpPool\.findMany/)
  assert.doesNotMatch(ipam, /tx\.nodeIpPool\.(upsert|deleteMany|updateMany)/)
  assert.doesNotMatch(ipam, /tx\.productIpPool\.(upsert|deleteMany|updateMany)/)
  assert.match(migration, /INSERT INTO "pool_node_assignments"/)
  assert.match(migration, /INSERT INTO "pool_product_assignments"/)
})

test("admin IP override and individual address delete are implemented", () => {
  const orchestrator = read("lib/vm-network-orchestrator.ts")
  const route = read("app/api/admin/vms/[id]/network/change-primary-ip/route.ts")
  const deleteRoute = read("app/api/admin/ip-pools/[id]/allocations/[allocationId]/route.ts")
  const available = read("app/api/admin/vms/[id]/network/available-ips/route.ts")
  assert.match(orchestrator, /forceAssign/)
  assert.match(orchestrator, /takeoverExisting/)
  assert.match(orchestrator, /releaseDuplicateIpOwnership/)
  assert.match(route, /manualGateway/)
  assert.match(deleteRoute, /IP_ALLOCATION_DELETE_ADDRESS/)
  assert.match(deleteRoute, /vmIpAssignment\.updateMany/)
  assert.match(available, /mode: "override"/)
})

test("password reset falls back from SMTP to WhatsApp and expires in 15 minutes", () => {
  const helper = read("lib/auth/password-reset-delivery.ts")
  const forgot = read("app/api/auth/forgot-password/route.ts")
  const admin = read("app/api/admin/customers/[id]/reset-password/route.ts")
  assert.match(helper, /PASSWORD_RESET_EXPIRES_MINUTES = 15/)
  assert.match(helper, /"Password Reset"/)
  assert.match(helper, /sendTemplateEmail/)
  assert.match(helper, /sendWhatsAppText/)
  assert.match(helper, /No SMTP or WhatsApp reset channel/)
  assert.match(forgot, /deliverPasswordResetLink/)
  assert.match(admin, /warning: delivery\.warning/)
})

test("Evolution client has production send fallback and real WhatsApp test script", () => {
  const client = read("lib/whatsapp/evolution-client.ts")
  const evolution = read("lib/whatsapp/evolution.ts")
  const script = read("scripts/whatsapp-production-test.ts")
  const pkg = read("package.json")
  assert.match(client, /textMessage: \{ text: input\.text \}/)
  assert.match(client, /shouldRetryLegacyTextPayload/)
  assert.match(client, /instanceName/)
  assert.match(evolution, /send_endpoint_valid/)
  assert.match(evolution, /real_send_accepted/)
  assert.match(script, /sendEvolutionText/)
  assert.match(script, /registerWebhook: true/)
  assert.match(pkg, /test:whatsapp/)
})

test("Cloudflare automation is non-destructive and direct tunnel mode has no public app port", () => {
  const auto = read("scripts/cloudflare-auto.mjs")
  const compose = read("docker-compose.yml")
  const env = read(".env.example")
  const manager = read("lib/cloudflare-tunnel-manager.ts")
  assert.doesNotMatch(auto, /method: "DELETE"/)
  assert.match(auto, /action: "conflict"/)
  assert.match(compose, /profiles: \["direct-cloudflare"\]/)
  assert.match(compose, /cloudflared:/)
  assert.match(compose, /expose:\n      - "3000"/)
  assert.doesNotMatch(compose, /\$\{APP_PORT:-3000\}:3000/)
  assert.match(env, /CLOUDFLARE_ONLY_MODE/)
  assert.match(env, /DIRECT_CLOUDFLARE_MODE/)
  assert.match(manager, /understandDnsChanges/)
  assert.match(manager, /generateCloudflareTunnelArtifacts/)
  assert.match(manager, /dnsDeletionAutomatic: false/)
  assert.match(manager, /requiredBeforeNginxRemoval/)
})

test("security report and Proxmox live SSE endpoints are present", () => {
  const security = read("app/api/admin/security/report/route.ts")
  const page = read("app/admin/security/page.tsx")
  const sse = read("app/api/admin/proxmox/live/stream/route.ts")
  const watcher = read("scripts/proxmox-event-watcher.ts")
  const realtime = read("lib/vm-network-orchestrator.ts")
  assert.match(security, /fail2ban/)
  assert.match(security, /secretScanner/)
  assert.match(security, /cloudflareTunnel/)
  assert.match(security, /openPorts/)
  assert.match(security, /sslHealth/)
  assert.match(page, /Security Report/)
  assert.match(sse, /text\/event-stream|SSE_HEADERS/)
  assert.match(sse, /targetLatencyMs/)
  assert.match(sse, /measuredLagMs/)
  assert.match(watcher, /PROXMOX_EVENT_WATCH_MS \|\| 250/)
  assert.match(realtime, /publishRealtimeEvent\(realtimeChannels\.proxmoxEvents/)
})

test("platform health repair has one admin action and automatic worker wiring", () => {
  const route = read("app/api/admin/system/health/repair/route.ts")
  const helper = read("lib/platform-health-repair.ts")
  const page = read("app/admin/system/health/page.tsx")
  const worker = read("scripts/platform-health-repair-worker.ts")
  const pkg = read("package.json")
  assert.match(route, /runPlatformHealthRepair/)
  assert.match(helper, /recoverProvisionableOrders/)
  assert.match(helper, /repairPaidOrdersMissingVmLinks/)
  assert.match(helper, /scanVmInfrastructure/)
  assert.match(helper, /runVmNetworkValidationWorker/)
  assert.match(page, /SystemHealthRepairButton/)
  assert.match(worker, /platform-health-repair/)
  assert.match(pkg, /repair:platform-health/)
})

test("health route allows expected PM2 companion services without hiding unknown extras", () => {
  const route = read("app/api/health/route.ts")
  assert.match(route, /ALLOWED_PM2_EXTRA_APPS/)
  assert.match(route, /zws-vnc-proxy,zws-proxmox-events/)
  assert.match(route, /unknownExtras/)
  assert.match(route, /unknownExtras\.length === 0/)
})
