export const WHATSAPP_TEMPLATE_KEYS = {
  AUTH_LOGIN_OTP: "auth_login_otp",
  AUTH_SIGNUP_OTP: "auth_signup_otp",
  AUTH_PASSWORD_RESET: "auth_password_reset",
  AUTH_DEVICE_VERIFY: "auth_device_verify",
  AUTH_LOGIN_SUCCESS: "auth_login_success",
  AUTH_FAILED_LOGIN: "auth_failed_login",
  AUTH_NEW_DEVICE: "auth_new_device",
  LOGIN_ALERT: "login_alert",
  SECURITY_ALERT: "security_alert",
  MAINTENANCE_ALERT: "maintenance_alert",
  INVOICE_READY: "invoice_ready",
  INVOICE_REMINDER: "invoice_reminder",
  PAYMENT_SUCCESS: "payment_success",
  PAYMENT_FAILED: "payment_failed",
  VPS_DEPLOYED: "vps_deployed",
  VPS_REINSTALL_STARTED: "vps_reinstall_started",
  VPS_REINSTALL_COMPLETED: "vps_reinstall_completed",
  RDP_DELIVERED: "rdp_delivered",
  SERVICE_SUSPENDED: "service_suspended",
  SERVICE_OPERATION_FAILED: "service_operation_failed",
  RENEWAL_REMINDER: "renewal_reminder",
  SUPPORT_REPLY: "support_reply",
  TICKET_UPDATE: "ticket_update",
  CAMPAIGN_PROMO: "campaign_promo",
  ONBOARDING_WELCOME: "onboarding_welcome",
  ABANDONED_CART: "abandoned_cart",
  ADMIN_TEST: "admin_test",
  SYSTEM_FALLBACK: "system_modern_fallback",
  CAMPAIGN_CUSTOM: "campaign_custom",
  PROVISIONING_UPDATE: "provisioning_update",
  LOW_BALANCE: "low_balance",
  ADDITIONAL_IP_ACTIVATED: "additional_ip_activated",
  BANDWIDTH_ADDON_ACTIVATED: "bandwidth_addon_activated",
  SNAPSHOT_ADDON_ACTIVATED: "snapshot_addon_activated",
  BACKUP_ADDON_ACTIVATED: "backup_addon_activated",
  BACKUP_COMPLETED: "backup_completed",
  BACKUP_FAILED: "backup_failed",
} as const

export type WhatsAppTemplateKey = typeof WHATSAPP_TEMPLATE_KEYS[keyof typeof WHATSAPP_TEMPLATE_KEYS]

export const LEGACY_WHATSAPP_TEMPLATE_KEY_ALIASES: Record<string, WhatsAppTemplateKey> = {
  login_otp: WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_OTP,
  signup_otp: WHATSAPP_TEMPLATE_KEYS.AUTH_SIGNUP_OTP,
  password_reset_otp: WHATSAPP_TEMPLATE_KEYS.AUTH_PASSWORD_RESET,
  password_reset: WHATSAPP_TEMPLATE_KEYS.AUTH_PASSWORD_RESET,
  device_verification_otp: WHATSAPP_TEMPLATE_KEYS.AUTH_DEVICE_VERIFY,
  login_alert: WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_SUCCESS,
  security_login_success: WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_SUCCESS,
  failed_login: WHATSAPP_TEMPLATE_KEYS.AUTH_FAILED_LOGIN,
  new_device: WHATSAPP_TEMPLATE_KEYS.AUTH_NEW_DEVICE,
  mobile_verification: WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_OTP,
  transaction_otp: WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_OTP,
  service_active: WHATSAPP_TEMPLATE_KEYS.VPS_DEPLOYED,
  service_provisioning: WHATSAPP_TEMPLATE_KEYS.PROVISIONING_UPDATE,
  suspension_warning: WHATSAPP_TEMPLATE_KEYS.SERVICE_SUSPENDED,
  renewal_invoice: WHATSAPP_TEMPLATE_KEYS.RENEWAL_REMINDER,
  support_ticket_created: WHATSAPP_TEMPLATE_KEYS.TICKET_UPDATE,
  campaign_custom: WHATSAPP_TEMPLATE_KEYS.CAMPAIGN_CUSTOM,
}

export const REQUIRED_WHATSAPP_TEMPLATE_KEYS: WhatsAppTemplateKey[] = [
  WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_OTP,
  WHATSAPP_TEMPLATE_KEYS.AUTH_SIGNUP_OTP,
  WHATSAPP_TEMPLATE_KEYS.AUTH_PASSWORD_RESET,
  WHATSAPP_TEMPLATE_KEYS.AUTH_DEVICE_VERIFY,
  WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_SUCCESS,
  WHATSAPP_TEMPLATE_KEYS.AUTH_FAILED_LOGIN,
  WHATSAPP_TEMPLATE_KEYS.AUTH_NEW_DEVICE,
  WHATSAPP_TEMPLATE_KEYS.LOGIN_ALERT,
  WHATSAPP_TEMPLATE_KEYS.SECURITY_ALERT,
  WHATSAPP_TEMPLATE_KEYS.MAINTENANCE_ALERT,
  WHATSAPP_TEMPLATE_KEYS.INVOICE_READY,
  WHATSAPP_TEMPLATE_KEYS.INVOICE_REMINDER,
  WHATSAPP_TEMPLATE_KEYS.PAYMENT_SUCCESS,
  WHATSAPP_TEMPLATE_KEYS.PAYMENT_FAILED,
  WHATSAPP_TEMPLATE_KEYS.VPS_DEPLOYED,
  WHATSAPP_TEMPLATE_KEYS.RDP_DELIVERED,
  WHATSAPP_TEMPLATE_KEYS.SERVICE_SUSPENDED,
  WHATSAPP_TEMPLATE_KEYS.SERVICE_OPERATION_FAILED,
  WHATSAPP_TEMPLATE_KEYS.RENEWAL_REMINDER,
  WHATSAPP_TEMPLATE_KEYS.SUPPORT_REPLY,
  WHATSAPP_TEMPLATE_KEYS.TICKET_UPDATE,
  WHATSAPP_TEMPLATE_KEYS.CAMPAIGN_PROMO,
  WHATSAPP_TEMPLATE_KEYS.ONBOARDING_WELCOME,
  WHATSAPP_TEMPLATE_KEYS.ABANDONED_CART,
  WHATSAPP_TEMPLATE_KEYS.ADMIN_TEST,
  WHATSAPP_TEMPLATE_KEYS.SYSTEM_FALLBACK,
  WHATSAPP_TEMPLATE_KEYS.ADDITIONAL_IP_ACTIVATED,
  WHATSAPP_TEMPLATE_KEYS.BANDWIDTH_ADDON_ACTIVATED,
  WHATSAPP_TEMPLATE_KEYS.SNAPSHOT_ADDON_ACTIVATED,
  WHATSAPP_TEMPLATE_KEYS.BACKUP_ADDON_ACTIVATED,
]

export const OTP_WHATSAPP_TEMPLATE_KEYS = [
  WHATSAPP_TEMPLATE_KEYS.AUTH_LOGIN_OTP,
  WHATSAPP_TEMPLATE_KEYS.AUTH_SIGNUP_OTP,
  WHATSAPP_TEMPLATE_KEYS.AUTH_PASSWORD_RESET,
  WHATSAPP_TEMPLATE_KEYS.AUTH_DEVICE_VERIFY,
] as const

function normalizeTemplateKey(input: string) {
  return String(input || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_ -]/g, "")
    .replace(/[\s-]+/g, "_")
    .replace(/^_+|_+$/g, "")
}

export function canonicalWhatsAppTemplateKey(input: string | null | undefined) {
  const normalized = normalizeTemplateKey(String(input || WHATSAPP_TEMPLATE_KEYS.SYSTEM_FALLBACK))
  return LEGACY_WHATSAPP_TEMPLATE_KEY_ALIASES[normalized] || normalized
}
